name: chengdu iptv build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install m3u8
          pip install bs4
          pip install lxml
          pip install html5lib
          pip install strict-rfc3339

      - name: Build home
        env:
          LAN_ADDRESS: ${{ vars.LAN_ADDRESS }}
        run: |
          python3 ./script/home.py

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add .
          git commit -m 'Update' || echo "nothing to commit"
          git push || echo "nothing to push"



